# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd6e46478fa2edea00ade421bfecc1997f15b7a4a2863a374ff1f8a667b4ce5cbe185afb5349fbb934967665490e1f1cdab3feb59ea6e4706af709c2a7132a56

test:
  secret_key_base: 6271fe20f1dbc6a2314d79fdfa962f7d8a5d8aef5a6187c15d64038f923f69637cae63143995a347a9c345f925cd822ada96abd2091b6304f4b498d81c6fb41d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
